_format_version: "3.0"

services:
  - name: auth-service
    url: http://auth:5001
    routes:
      - name: auth-route
        paths:
          - /api/v1/auth
        strip_path: true

  - name: notes-service
    url: http://notes:8082
    routes:
      - name: notes-route
        paths:
          - /api/v1/notes
        strip_path: true
