_format_version: "3.0"

services:
  - name: auth-service
    url: http://auth:5001
    routes:
      - name: auth-route
        paths:
          - /api/auth
        strip_path: false

  - name: notes-service
    url: http://notes:8082
    routes:
      - name: notes-route
        paths:
          - /api/notes
        strip_path: false
