/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as AppChatRouteImport } from './routes/_app/chat'
import { Route as AppNotesRouteRouteImport } from './routes/_app/notes/route'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppTagsRouteImport } from './routes/_app/tags'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as AppNotesIndexRouteImport } from './routes/_app/notes/index'
import { Route as AppNotesNoteIdRouteImport } from './routes/_app/notes/$noteId'
import { Route as AppNotesArchiveRouteImport } from './routes/_app/notes/archive'
import { Route as AppNotesCreateRouteImport } from './routes/_app/notes/create'
import { Route as AppNotesFavoritesRouteImport } from './routes/_app/notes/favorites'
import { Route as AppNotesTrashRouteImport } from './routes/_app/notes/trash'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppNotesRouteRoute = AppNotesRouteRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppTagsRoute = AppTagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => AppRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AppNotesIndexRoute = AppNotesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppNotesRouteRoute,
} as any)
const AppNotesNoteIdRoute = AppNotesNoteIdRouteImport.update({
  id: '/$noteId',
  path: '/$noteId',
  getParentRoute: () => AppNotesRouteRoute,
} as any)
const AppNotesArchiveRoute = AppNotesArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => AppNotesRouteRoute,
} as any)
const AppNotesCreateRoute = AppNotesCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AppNotesRouteRoute,
} as any)
const AppNotesFavoritesRoute = AppNotesFavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => AppNotesRouteRoute,
} as any)
const AppNotesTrashRoute = AppNotesTrashRouteImport.update({
  id: '/trash',
  path: '/trash',
  getParentRoute: () => AppNotesRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/notes': typeof AppNotesRouteRouteWithChildren
  '/chat': typeof AppChatRoute
  '/profile': typeof AppProfileRoute
  '/settings': typeof AppSettingsRoute
  '/tags': typeof AppTagsRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/notes/$noteId': typeof AppNotesNoteIdRoute
  '/notes/archive': typeof AppNotesArchiveRoute
  '/notes/create': typeof AppNotesCreateRoute
  '/notes/favorites': typeof AppNotesFavoritesRoute
  '/notes/trash': typeof AppNotesTrashRoute
  '/notes/': typeof AppNotesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof AppChatRoute
  '/profile': typeof AppProfileRoute
  '/settings': typeof AppSettingsRoute
  '/tags': typeof AppTagsRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/notes/$noteId': typeof AppNotesNoteIdRoute
  '/notes/archive': typeof AppNotesArchiveRoute
  '/notes/create': typeof AppNotesCreateRoute
  '/notes/favorites': typeof AppNotesFavoritesRoute
  '/notes/trash': typeof AppNotesTrashRoute
  '/notes': typeof AppNotesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteRouteWithChildren
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_app/notes': typeof AppNotesRouteRouteWithChildren
  '/_app/chat': typeof AppChatRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/tags': typeof AppTagsRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_app/notes/$noteId': typeof AppNotesNoteIdRoute
  '/_app/notes/archive': typeof AppNotesArchiveRoute
  '/_app/notes/create': typeof AppNotesCreateRoute
  '/_app/notes/favorites': typeof AppNotesFavoritesRoute
  '/_app/notes/trash': typeof AppNotesTrashRoute
  '/_app/notes/': typeof AppNotesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/notes'
    | '/chat'
    | '/profile'
    | '/settings'
    | '/tags'
    | '/login'
    | '/register'
    | '/notes/$noteId'
    | '/notes/archive'
    | '/notes/create'
    | '/notes/favorites'
    | '/notes/trash'
    | '/notes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat'
    | '/profile'
    | '/settings'
    | '/tags'
    | '/login'
    | '/register'
    | '/notes/$noteId'
    | '/notes/archive'
    | '/notes/create'
    | '/notes/favorites'
    | '/notes/trash'
    | '/notes'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_auth'
    | '/_app/notes'
    | '/_app/chat'
    | '/_app/profile'
    | '/_app/settings'
    | '/_app/tags'
    | '/_auth/login'
    | '/_auth/register'
    | '/_app/notes/$noteId'
    | '/_app/notes/archive'
    | '/_app/notes/create'
    | '/_app/notes/favorites'
    | '/_app/notes/trash'
    | '/_app/notes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/chat': {
      id: '/_app/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/notes': {
      id: '/_app/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof AppNotesRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/tags': {
      id: '/_app/tags'
      path: '/tags'
      fullPath: '/tags'
      preLoaderRoute: typeof AppTagsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_app/notes/': {
      id: '/_app/notes/'
      path: '/'
      fullPath: '/notes/'
      preLoaderRoute: typeof AppNotesIndexRouteImport
      parentRoute: typeof AppNotesRouteRoute
    }
    '/_app/notes/$noteId': {
      id: '/_app/notes/$noteId'
      path: '/$noteId'
      fullPath: '/notes/$noteId'
      preLoaderRoute: typeof AppNotesNoteIdRouteImport
      parentRoute: typeof AppNotesRouteRoute
    }
    '/_app/notes/archive': {
      id: '/_app/notes/archive'
      path: '/archive'
      fullPath: '/notes/archive'
      preLoaderRoute: typeof AppNotesArchiveRouteImport
      parentRoute: typeof AppNotesRouteRoute
    }
    '/_app/notes/create': {
      id: '/_app/notes/create'
      path: '/create'
      fullPath: '/notes/create'
      preLoaderRoute: typeof AppNotesCreateRouteImport
      parentRoute: typeof AppNotesRouteRoute
    }
    '/_app/notes/favorites': {
      id: '/_app/notes/favorites'
      path: '/favorites'
      fullPath: '/notes/favorites'
      preLoaderRoute: typeof AppNotesFavoritesRouteImport
      parentRoute: typeof AppNotesRouteRoute
    }
    '/_app/notes/trash': {
      id: '/_app/notes/trash'
      path: '/trash'
      fullPath: '/notes/trash'
      preLoaderRoute: typeof AppNotesTrashRouteImport
      parentRoute: typeof AppNotesRouteRoute
    }
  }
}

interface AppNotesRouteRouteChildren {
  AppNotesNoteIdRoute: typeof AppNotesNoteIdRoute
  AppNotesArchiveRoute: typeof AppNotesArchiveRoute
  AppNotesCreateRoute: typeof AppNotesCreateRoute
  AppNotesFavoritesRoute: typeof AppNotesFavoritesRoute
  AppNotesTrashRoute: typeof AppNotesTrashRoute
  AppNotesIndexRoute: typeof AppNotesIndexRoute
}

const AppNotesRouteRouteChildren: AppNotesRouteRouteChildren = {
  AppNotesNoteIdRoute: AppNotesNoteIdRoute,
  AppNotesArchiveRoute: AppNotesArchiveRoute,
  AppNotesCreateRoute: AppNotesCreateRoute,
  AppNotesFavoritesRoute: AppNotesFavoritesRoute,
  AppNotesTrashRoute: AppNotesTrashRoute,
  AppNotesIndexRoute: AppNotesIndexRoute,
}

const AppNotesRouteRouteWithChildren = AppNotesRouteRoute._addFileChildren(
  AppNotesRouteRouteChildren,
)

interface AppRouteRouteChildren {
  AppNotesRouteRoute: typeof AppNotesRouteRouteWithChildren
  AppChatRoute: typeof AppChatRoute
  AppProfileRoute: typeof AppProfileRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTagsRoute: typeof AppTagsRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppNotesRouteRoute: AppNotesRouteRouteWithChildren,
  AppChatRoute: AppChatRoute,
  AppProfileRoute: AppProfileRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTagsRoute: AppTagsRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
