server:
   port: 8082

spring:
   datasource:
      url: jdbc:postgresql://localhost:5432/notes_db
      username: synapse
      password: root
   jpa:
      hibernate:
         ddl-auto: update
   # security:
   #    oauth2:
   #       resourceserver:
   #          jwt:
   #             jwk-set-uri: http://localhost:5001/api/auth/.well-known/jwks.json
