apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  labels:
    app: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      serviceAccountName: job-watcher-sa
      initContainers:
        - name: wait-for-postgres
          image: busybox:1.36
          command:
            [
              "sh",
              "-c",
              "until nc -z postgres 5432; do echo waiting for postgres...; sleep 2; done;",
            ]
        - name: wait-for-auth-seed
          image: bitnami/kubectl:latest
          command:
            - sh
            - -c
            - |
              until kubectl get job auth-seed-demo-acc >/dev/null 2>&1; do
                echo "Waiting for job auth-seed-demo-acc to be created..."
                sleep 2
              done
              kubectl wait --for=condition=complete job/auth-seed-demo-acc --timeout=120s
      containers:
        - name: synapse-auth
          image: auth
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5001
              protocol: TCP
          envFrom:
            - secretRef:
                name: auth-secrets
          resources:
            requests:
              cpu: "100m"
              memory: "96Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
      restartPolicy: Always
