apiVersion: v1
kind: Service
metadata:
  labels:
    app: kong
  name: kong
spec:
  type: LoadBalancer
  ports:
    - name: "8000"
      port: 8000
      targetPort: 8000
    - name: "8001"
      port: 8001
      targetPort: 8001
  selector:
    app: kong
