apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - rbac.yaml
  - ai-deployment.yaml
  - ai-migrate-job.yaml
  - ai-service.yaml
  - auth-deployment.yaml
  - auth-migrate-job.yaml
  - auth-seed-demo-acc-job.yaml
  - auth-service.yaml
  - kong-deployment.yaml
  - kong-configmap.yaml
  - kong-service.yaml
  - notes-deployment.yaml
  - notes-service.yaml
  - postgres-deployment.yaml
  - postgres-init-configmap.yaml
  - postgres-service.yaml
  - pgdata-pvc.yaml
  - rabbitmq-deployment.yaml
  - rabbitmq-service.yaml
  - rabbitmq-pvc.yaml
  - rabbitmq-configmap.yaml